/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <iencoder_task.h>
#include "main.h"
#include <stdio.h>

#include "cmsis_os2.h"

#include "stm32h7xx_sysclock.h"

#include "terminal.h"
#include "usb_device.h"

#include "modules.h"

#include "storage_task.h"
#include "control_task.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

osThreadId_t controlTaskHandle;
const osThreadAttr_t controlTask_attributes = {
  .name = "controlTask",
  .priority = (osPriority_t) osPriorityNormal3,
  .stack_size = 768 * 4
};

osThreadId_t iencoderTaskHandle;
const osThreadAttr_t iencoderTask_attributes = {
  .name = "iencoderTask",
  .priority = (osPriority_t) osPriorityNormal1,
  .stack_size = 128 * 4
};

osThreadId_t storageTaskHandle;
const osThreadAttr_t storageTask_attributes = {
  .name = "storageTask",
  .priority = (osPriority_t) osPriorityNormal2,
  .stack_size = 768 * 4
};

#define CMD_QUEUE_OBJECTS 3
#define CMD_QUEUE_OBJ_SIZE 256
osMessageQueueId_t cmdQueueHandler;
const osMessageQueueAttr_t cmdQueue = {
	.name = "CmdQueue"
};

#define CAMERA_QUEUE_OBJECTS 1
osMessageQueueId_t cameraQueueHandler;
const osMessageQueueAttr_t cameraQueue = {
	.name = "CamaraQueue"
};

osEventFlagsId_t cameraEvtId;                 // event flags id

osSemaphoreId_t calibrationSem;					// semaphore id


static void CPU_CACHE_Enable(void)
{
  /* Enable I-Cache */
  SCB_EnableICache();

  /* Enable D-Cache */
  SCB_EnableDCache();
}

int main(void)
{
  //CPU_CACHE_Enable();

  HAL_Init();
  /* Configure the system clock */
  SystemClock_Config();

  terminal_init();
  uartprintf("UART terminal init");
  //storage_init();
  uartprintf("Storage init");
  HAL_Delay(100);
  uartprintf("USB init start");
  usb_comp_dev_init();
  uartprintf("USB init finish");
  // Нужно проверить, что COM порт настроился и только потом отправлять
  //uartprintf("USB terminal init");
  //usbprintf("UART terminal init");
  //usbprintf("USB terminal init");

  osKernelInitialize();

  cmdQueueHandler = osMessageQueueNew (CMD_QUEUE_OBJECTS, CMD_QUEUE_OBJ_SIZE, &cmdQueue);
  cameraQueueHandler = osMessageQueueNew (CAMERA_QUEUE_OBJECTS, sizeof(CameraQueueObj_t) , &cameraQueue);

  cameraEvtId = osEventFlagsNew(NULL);
  if (cameraEvtId == NULL) {
    usbprintf("Camera Event Flag object not created");
  }

  calibrationSem = osSemaphoreNew(1U, 0U, NULL);
  if (calibrationSem == NULL) {
	  usbprintf("Semaphore object not created");
  }

  controlTaskHandle = osThreadNew(ControlTask, NULL, &controlTask_attributes);
  iencoderTaskHandle = osThreadNew(IencoderTask, NULL, &iencoderTask_attributes);
  storageTaskHandle = osThreadNew(StorageTask, NULL, &storageTask_attributes);

  osKernelStart();

  /* Loop forever */
  while(1){}
}


/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  uartprintf("Error Handler");
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
